// ignore_for_file: constant_identifier_names, camel_case_types
const commonParams = ['sessionId', 'userId', 'lang', 'device', 'os'];

Map<String, Map<String, dynamic>> SEGMENTIFY_EVENT_PARAMS = {
  'PAGE_VIEW': {
    'requiredParams': [...commonParams],
    'optionalParams': ['category', 'subCategory'],
  },
  'PRODUCT_VIEW': {
    'requiredParams': ['productId', ...commonParams],
    'optionalParams': [
      'title',
      'url',
      'mUrl',
      'image',
      'imageXS',
      'imageS',
      'imageM',
      'imageL',
      'imageXL',
      'additionalImages',
      'mainCategory',
      'category',
      'categories',
      'price',
      'oldPrice',
      'specialPrice',
      'lastUpdateTime',
      'inStock',
      'stockCount',
      'stockRatio',
      'stockStatus',
      'brand',
      'gender',
      'labels',
      'sizes',
      'allSizes',
      'colors',
      'publishTime',
      'source',
      'noUpdate',
      'activeBanners',
      'groupId',
      'scoreCount',
      'reviewCount',
      'subSource',
      'paramsList',
    ],
  },
  'BASKET_OPERATIONS': {
    'requiredParams': ['productId', 'basketId', 'step', ...commonParams],
    'optionalParams': ['price', 'quantity', 'size', 'activeBanners'],
  },
  'CHECKOUT': {
    'requiredParams': ['totalPrice', 'basketId', 'step', ...commonParams],
    'optionalParams': [
      'productList',
      'orderNo',
      'paymentType',
      'activeBanners',
      'cartUrl',
      'totalDiscount',
      'discounts',
      'shipment',
      'tax',
      'coupon',
    ],
  },
  'USER_OPERATIONS': {
    'requiredParams': ['step', ...commonParams],
    'optionalParams': [
      'username',
      'fullName',
      'phone',
      'gender',
      'birthDate',
      'segments',
      'memberSince',
      'service',
      'isRegistered',
      'isLogin',
      'location',
      'emailNtf',
      'mailTest',
      'pushTest',
      'custom',
      'external',
      'userIysPermissions',
      'lastSearchDeletedKeywords',
    ],
  },
  'CUSTOM_EVENT': {
    'requiredParams': ['type', ...commonParams],
    'optionalParams': [],
  },
  'INTERACTION': {
    'requiredParams': ['type'],
    'optionalParams': ['interactionId', 'instanceId', ...commonParams],
  },
  'SEARCH': {
    'requiredParams': ['sessionId', 'userId', ...commonParams],
    'optionalParams': [
      'query',
      'type',
      'ordering',
      'filters',
      'trigger',
      'service',
      'mode',
    ],
  },
  'GAMIFICATION': {
    'requiredParams': ['type', ...commonParams],
    'optionalParams': ['name', 'used', 'record'],
  },
};
